// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NewId")]
[assembly: AssemblyDescriptionAttribute("NewId is an ordered 128-bit unique identifier generator using the Flake algorithm.")]
[assembly: AssemblyProductAttribute("NewId")]
[assembly: AssemblyVersionAttribute("3.0.1.0")]
[assembly: AssemblyFileVersionAttribute("3.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("3.0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NewId";
        internal const System.String AssemblyDescription = "NewId is an ordered 128-bit unique identifier generator using the Flake algorithm.";
        internal const System.String AssemblyProduct = "NewId";
        internal const System.String AssemblyVersion = "3.0.1.0";
        internal const System.String AssemblyFileVersion = "3.0.1.0";
        internal const System.String AssemblyInformationalVersion = "3.0.1.0";
    }
}
